services:
  # Web service for Django app
  - type: web
    name: vidyai
    runtime: python
    buildCommand: pip install -r requirements.txt && cd VidyAI && python manage.py collectstatic --no-input
    startCommand: cd VidyAI && gunicorn vidyai.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GEMINI_API_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: vidyai.settings
      - key: DATABASE_URL
        fromDatabase:
          name: vidyai_db
          property: connectionString
      - key: RENDER
        value: "true"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG 
        value: "false"
    autoDeploy: true
    # Add post-deploy hooks to run migrations
    postDeploy:
      - command: cd VidyAI && python manage.py migrate

# Database service for PostgreSQL
databases:
  - name: vidyai_db
    plan: free
    databaseName: vidyai
    user: vidyai
